spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    platform: oracle
    driverClassName: oracle.jdbc.OracleDriver
    database-platform: org.hibernate.dialect.OracleDialect
    username: SYSTEM
    password: Newpassword1
  liquibase:
    change-log: classpath:changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
