package ru.elenacherev.librarymanager.config

import org.springframework.data.jpa.repository.config.EnableJpaAuditing
import org.springframework.data.jpa.repository.config.EnableJpaRepositories
import org.springframework.transaction.annotation.EnableTransactionManagement

@EnableJpaAuditing
@EnableJpaRepositories
@EnableTransactionManagement
class DatabaseConfig